# Describes the format for available DSPWorks services

set_fan_speed_tracked_state:
  name: Set fan speed tracked state
  description: Sets the tracked fan speed for a DSPWorks fan
  fields:
    entity_id:
      description: Name(s) of entities to set the tracked fan speed.
      example: "fan.living_room_fan"
      name: Entity
      required: true
      selector:
        entity:
          integration: dspworks_app
          domain: fan
    speed:
      required: true
      name: Fan Speed
      description: Fan Speed as %.
      example: 50
      selector:
        number:
          min: 0
          max: 100
          step: 1
          mode: slider

set_switch_power_tracked_state:
  name: Set switch power tracked state
  description: Sets the tracked power state of a DSPWorks switch
  fields:
    entity_id:
      description: Name(s) of entities to set the tracked power state of.
      example: "switch.whatever"
      name: Entity
      required: true
      selector:
        entity:
          integration: dspworks_app
          domain: switch
    power_state:
      required: true
      name: Power state
      description: Power state
      example: true
      selector:
        boolean:

set_light_power_tracked_state:
  name: Set light power tracked state
  description: Sets the tracked power state of a DSPWorks light
  fields:
    entity_id:
      description: Name(s) of entities to set the tracked power state of.
      example: "light.living_room_lights"
      name: Entity
      required: true
      selector:
        entity:
          integration: dspworks_app
          domain: light
    power_state:
      required: true
      name: Power state
      description: Power state
      example: true
      selector:
        boolean:

set_light_brightness_tracked_state:
  name: Set light brightness tracked state
  description: Sets the tracked brightness state of a DSPWorks light
  fields:
    entity_id:
      description: Name(s) of entities to set the tracked brightness state of.
      example: "light.living_room_lights"
      name: Entity
      required: true
      selector:
        entity:
          integration: dspworks_app
          domain: light
    brightness:
      required: true
      name: Brightness
      description: Brightness
      example: 50
      selector:
        number:
          min: 0
          max: 255
          step: 1
          mode: slider
